.pragma library

// Curated emoji dataset for the island-native picker. Each entry: { e: char,
// n: name, k: extra search keywords, c: category }. Not exhaustive (the long
// tail is rarely needed) but covers the everyday set across all categories with
// good search keywords. Rendered in colour via Noto Color Emoji.

var CATEGORIES = [
    { key: "recent",     icon: "\u{1F551}", name: "Recent" },
    { key: "smileys",    icon: "\u{1F600}", name: "Smileys & Emotion" },
    { key: "people",     icon: "\u{1F44B}", name: "People & Body" },
    { key: "animals",    icon: "\u{1F43B}", name: "Animals & Nature" },
    { key: "food",       icon: "\u{1F354}", name: "Food & Drink" },
    { key: "activities", icon: "⚽",    name: "Activities" },
    { key: "travel",     icon: "✈️", name: "Travel & Places" },
    { key: "objects",    icon: "\u{1F4A1}", name: "Objects" },
    { key: "symbols",    icon: "❤️", name: "Symbols" },
    { key: "flags",      icon: "\u{1F3C1}", name: "Flags" }
]

var EMOJI = [
    // ---- smileys & emotion ----
    { e: "😀", n: "grinning face", k: "smile happy", c: "smileys" },
    { e: "😃", n: "grinning face with big eyes", k: "happy smile joy", c: "smileys" },
    { e: "😄", n: "grinning face with smiling eyes", k: "happy laugh", c: "smileys" },
    { e: "😁", n: "beaming face", k: "grin happy", c: "smileys" },
    { e: "😆", n: "grinning squinting face", k: "laugh haha", c: "smileys" },
    { e: "😅", n: "grinning face with sweat", k: "laugh relief phew", c: "smileys" },
    { e: "🤣", n: "rolling on the floor laughing", k: "rofl lol funny", c: "smileys" },
    { e: "😂", n: "face with tears of joy", k: "lol laugh cry funny", c: "smileys" },
    { e: "🙂", n: "slightly smiling face", k: "smile", c: "smileys" },
    { e: "🙃", n: "upside down face", k: "silly sarcasm", c: "smileys" },
    { e: "😉", n: "winking face", k: "wink flirt", c: "smileys" },
    { e: "😊", n: "smiling face with smiling eyes", k: "blush happy", c: "smileys" },
    { e: "😇", n: "smiling face with halo", k: "angel innocent", c: "smileys" },
    { e: "🥰", n: "smiling face with hearts", k: "love adore", c: "smileys" },
    { e: "😍", n: "heart eyes", k: "love crush", c: "smileys" },
    { e: "🤩", n: "star struck", k: "starry eyes excited", c: "smileys" },
    { e: "😘", n: "face blowing a kiss", k: "kiss love", c: "smileys" },
    { e: "😗", n: "kissing face", k: "kiss", c: "smileys" },
    { e: "😋", n: "face savoring food", k: "yum tongue tasty", c: "smileys" },
    { e: "😛", n: "face with tongue", k: "tongue silly", c: "smileys" },
    { e: "😜", n: "winking face with tongue", k: "tongue wink silly", c: "smileys" },
    { e: "🤪", n: "zany face", k: "crazy goofy", c: "smileys" },
    { e: "😝", n: "squinting face with tongue", k: "tongue", c: "smileys" },
    { e: "🤑", n: "money mouth face", k: "rich dollar", c: "smileys" },
    { e: "🤗", n: "hugging face", k: "hug", c: "smileys" },
    { e: "🤭", n: "face with hand over mouth", k: "oops giggle", c: "smileys" },
    { e: "🤫", n: "shushing face", k: "quiet shh secret", c: "smileys" },
    { e: "🤔", n: "thinking face", k: "hmm think", c: "smileys" },
    { e: "🤨", n: "face with raised eyebrow", k: "skeptic suspicious", c: "smileys" },
    { e: "😐", n: "neutral face", k: "meh blank", c: "smileys" },
    { e: "😑", n: "expressionless face", k: "blank", c: "smileys" },
    { e: "😶", n: "face without mouth", k: "silent", c: "smileys" },
    { e: "😏", n: "smirking face", k: "smug", c: "smileys" },
    { e: "😒", n: "unamused face", k: "meh annoyed", c: "smileys" },
    { e: "🙄", n: "face with rolling eyes", k: "annoyed whatever", c: "smileys" },
    { e: "😬", n: "grimacing face", k: "awkward eek", c: "smileys" },
    { e: "😴", n: "sleeping face", k: "sleep tired zzz", c: "smileys" },
    { e: "😪", n: "sleepy face", k: "tired", c: "smileys" },
    { e: "😌", n: "relieved face", k: "calm content", c: "smileys" },
    { e: "😔", n: "pensive face", k: "sad", c: "smileys" },
    { e: "😕", n: "confused face", k: "unsure", c: "smileys" },
    { e: "🙁", n: "slightly frowning face", k: "sad", c: "smileys" },
    { e: "☹️", n: "frowning face", k: "sad", c: "smileys" },
    { e: "😣", n: "persevering face", k: "struggle", c: "smileys" },
    { e: "😖", n: "confounded face", k: "frustrated", c: "smileys" },
    { e: "😫", n: "tired face", k: "exhausted", c: "smileys" },
    { e: "😩", n: "weary face", k: "tired", c: "smileys" },
    { e: "🥺", n: "pleading face", k: "puppy eyes beg cute", c: "smileys" },
    { e: "😢", n: "crying face", k: "sad tear", c: "smileys" },
    { e: "😭", n: "loudly crying face", k: "sob bawl sad", c: "smileys" },
    { e: "😤", n: "face with steam from nose", k: "angry triumph", c: "smileys" },
    { e: "😠", n: "angry face", k: "mad", c: "smileys" },
    { e: "😡", n: "pouting face", k: "angry rage mad", c: "smileys" },
    { e: "🤬", n: "face with symbols on mouth", k: "swear curse angry", c: "smileys" },
    { e: "🤯", n: "exploding head", k: "mind blown shock", c: "smileys" },
    { e: "😳", n: "flushed face", k: "embarrassed", c: "smileys" },
    { e: "🥵", n: "hot face", k: "heat sweating", c: "smileys" },
    { e: "🥶", n: "cold face", k: "freezing", c: "smileys" },
    { e: "😱", n: "screaming in fear", k: "shock scared", c: "smileys" },
    { e: "😨", n: "fearful face", k: "scared", c: "smileys" },
    { e: "😰", n: "anxious face with sweat", k: "nervous", c: "smileys" },
    { e: "🥳", n: "partying face", k: "celebrate party hat", c: "smileys" },
    { e: "😎", n: "smiling face with sunglasses", k: "cool", c: "smileys" },
    { e: "🤓", n: "nerd face", k: "geek glasses", c: "smileys" },
    { e: "🧐", n: "face with monocle", k: "inspect", c: "smileys" },
    { e: "😷", n: "face with medical mask", k: "sick mask", c: "smileys" },
    { e: "🤒", n: "face with thermometer", k: "sick fever", c: "smileys" },
    { e: "🤢", n: "nauseated face", k: "sick gross", c: "smileys" },
    { e: "🤮", n: "vomiting face", k: "sick puke", c: "smileys" },
    { e: "🥴", n: "woozy face", k: "drunk dizzy", c: "smileys" },
    { e: "😵", n: "dizzy face", k: "knocked out", c: "smileys" },
    { e: "🤠", n: "cowboy hat face", k: "yeehaw", c: "smileys" },
    { e: "👻", n: "ghost", k: "boo halloween", c: "smileys" },
    { e: "💀", n: "skull", k: "dead death", c: "smileys" },
    { e: "👽", n: "alien", k: "ufo space", c: "smileys" },
    { e: "🤖", n: "robot", k: "bot ai", c: "smileys" },
    { e: "💩", n: "pile of poo", k: "poop crap", c: "smileys" },
    { e: "🤡", n: "clown face", k: "joker", c: "smileys" },
    { e: "😈", n: "smiling face with horns", k: "devil evil", c: "smileys" },
    { e: "🤥", n: "lying face", k: "liar pinocchio", c: "smileys" },

    // ---- people & body ----
    { e: "👋", n: "waving hand", k: "hi hello bye wave", c: "people" },
    { e: "🤚", n: "raised back of hand", k: "stop", c: "people" },
    { e: "✋", n: "raised hand", k: "stop high five", c: "people" },
    { e: "🖐️", n: "hand with fingers splayed", k: "five", c: "people" },
    { e: "👌", n: "ok hand", k: "okay perfect", c: "people" },
    { e: "🤌", n: "pinched fingers", k: "italian", c: "people" },
    { e: "🤏", n: "pinching hand", k: "small tiny", c: "people" },
    { e: "✌️", n: "victory hand", k: "peace two", c: "people" },
    { e: "🤞", n: "crossed fingers", k: "luck hope", c: "people" },
    { e: "🤟", n: "love you gesture", k: "ily", c: "people" },
    { e: "🤘", n: "sign of the horns", k: "rock metal", c: "people" },
    { e: "🤙", n: "call me hand", k: "shaka hang loose", c: "people" },
    { e: "👈", n: "backhand index pointing left", k: "point left", c: "people" },
    { e: "👉", n: "backhand index pointing right", k: "point right", c: "people" },
    { e: "👆", n: "backhand index pointing up", k: "point up", c: "people" },
    { e: "👇", n: "backhand index pointing down", k: "point down", c: "people" },
    { e: "☝️", n: "index pointing up", k: "one", c: "people" },
    { e: "👍", n: "thumbs up", k: "like yes approve good", c: "people" },
    { e: "👎", n: "thumbs down", k: "dislike no bad", c: "people" },
    { e: "✊", n: "raised fist", k: "power solidarity", c: "people" },
    { e: "👊", n: "oncoming fist", k: "punch bro fist bump", c: "people" },
    { e: "🤛", n: "left facing fist", k: "fist bump", c: "people" },
    { e: "🤜", n: "right facing fist", k: "fist bump", c: "people" },
    { e: "👏", n: "clapping hands", k: "applause bravo clap", c: "people" },
    { e: "🙌", n: "raising hands", k: "celebrate hooray praise", c: "people" },
    { e: "👐", n: "open hands", k: "hug", c: "people" },
    { e: "🤲", n: "palms up together", k: "pray cupped", c: "people" },
    { e: "🤝", n: "handshake", k: "deal agreement", c: "people" },
    { e: "🙏", n: "folded hands", k: "pray thanks please", c: "people" },
    { e: "✍️", n: "writing hand", k: "write", c: "people" },
    { e: "💪", n: "flexed biceps", k: "strong muscle gym", c: "people" },
    { e: "🦾", n: "mechanical arm", k: "robot prosthetic", c: "people" },
    { e: "👀", n: "eyes", k: "look see watch", c: "people" },
    { e: "👁️", n: "eye", k: "look", c: "people" },
    { e: "🧠", n: "brain", k: "smart mind", c: "people" },
    { e: "👶", n: "baby", k: "infant", c: "people" },
    { e: "🧒", n: "child", k: "kid", c: "people" },
    { e: "👦", n: "boy", k: "kid", c: "people" },
    { e: "👧", n: "girl", k: "kid", c: "people" },
    { e: "🧑", n: "person", k: "adult", c: "people" },
    { e: "👨", n: "man", k: "male guy", c: "people" },
    { e: "👩", n: "woman", k: "female lady", c: "people" },
    { e: "🧔", n: "person beard", k: "man", c: "people" },
    { e: "👮", n: "police officer", k: "cop", c: "people" },
    { e: "🕵️", n: "detective", k: "spy", c: "people" },
    { e: "👨‍💻", n: "man technologist", k: "developer coder programmer", c: "people" },
    { e: "👩‍💻", n: "woman technologist", k: "developer coder programmer", c: "people" },
    { e: "🦸", n: "superhero", k: "hero", c: "people" },
    { e: "🦹", n: "supervillain", k: "villain", c: "people" },
    { e: "🎅", n: "santa claus", k: "christmas xmas", c: "people" },
    { e: "🧑‍🎄", n: "mx claus", k: "christmas", c: "people" },

    // ---- animals & nature ----
    { e: "🐶", n: "dog face", k: "puppy", c: "animals" },
    { e: "🐱", n: "cat face", k: "kitten", c: "animals" },
    { e: "🐭", n: "mouse face", k: "", c: "animals" },
    { e: "🐹", n: "hamster", k: "", c: "animals" },
    { e: "🐰", n: "rabbit face", k: "bunny", c: "animals" },
    { e: "🦊", n: "fox", k: "", c: "animals" },
    { e: "🐻", n: "bear", k: "", c: "animals" },
    { e: "🐼", n: "panda", k: "", c: "animals" },
    { e: "🐨", n: "koala", k: "", c: "animals" },
    { e: "🐯", n: "tiger face", k: "", c: "animals" },
    { e: "🦁", n: "lion", k: "", c: "animals" },
    { e: "🐮", n: "cow face", k: "", c: "animals" },
    { e: "🐷", n: "pig face", k: "", c: "animals" },
    { e: "🐸", n: "frog", k: "", c: "animals" },
    { e: "🐵", n: "monkey face", k: "", c: "animals" },
    { e: "🐔", n: "chicken", k: "", c: "animals" },
    { e: "🐧", n: "penguin", k: "linux", c: "animals" },
    { e: "🐦", n: "bird", k: "", c: "animals" },
    { e: "🦆", n: "duck", k: "", c: "animals" },
    { e: "🦉", n: "owl", k: "", c: "animals" },
    { e: "🐴", n: "horse face", k: "", c: "animals" },
    { e: "🦄", n: "unicorn", k: "magic", c: "animals" },
    { e: "🐝", n: "honeybee", k: "bee", c: "animals" },
    { e: "🐛", n: "bug", k: "caterpillar", c: "animals" },
    { e: "🦋", n: "butterfly", k: "", c: "animals" },
    { e: "🐌", n: "snail", k: "slow", c: "animals" },
    { e: "🐢", n: "turtle", k: "", c: "animals" },
    { e: "🐍", n: "snake", k: "python", c: "animals" },
    { e: "🐙", n: "octopus", k: "", c: "animals" },
    { e: "🦈", n: "shark", k: "", c: "animals" },
    { e: "🐬", n: "dolphin", k: "", c: "animals" },
    { e: "🐳", n: "spouting whale", k: "docker", c: "animals" },
    { e: "🐟", n: "fish", k: "", c: "animals" },
    { e: "🦀", n: "crab", k: "rust", c: "animals" },
    { e: "🐊", n: "crocodile", k: "alligator", c: "animals" },
    { e: "🌵", n: "cactus", k: "plant desert", c: "animals" },
    { e: "🌲", n: "evergreen tree", k: "pine", c: "animals" },
    { e: "🌳", n: "deciduous tree", k: "tree", c: "animals" },
    { e: "🌴", n: "palm tree", k: "beach", c: "animals" },
    { e: "🌱", n: "seedling", k: "plant sprout", c: "animals" },
    { e: "🌿", n: "herb", k: "leaf plant", c: "animals" },
    { e: "🍀", n: "four leaf clover", k: "luck", c: "animals" },
    { e: "🌹", n: "rose", k: "flower love", c: "animals" },
    { e: "🌻", n: "sunflower", k: "flower", c: "animals" },
    { e: "🌸", n: "cherry blossom", k: "flower sakura", c: "animals" },
    { e: "🌷", n: "tulip", k: "flower", c: "animals" },
    { e: "🍄", n: "mushroom", k: "fungus", c: "animals" },
    { e: "🌍", n: "globe europe africa", k: "earth world", c: "animals" },
    { e: "🌙", n: "crescent moon", k: "night", c: "animals" },
    { e: "⭐", n: "star", k: "favorite", c: "animals" },
    { e: "🌟", n: "glowing star", k: "sparkle", c: "animals" },
    { e: "✨", n: "sparkles", k: "shine magic clean", c: "animals" },
    { e: "⚡", n: "high voltage", k: "lightning bolt fast", c: "animals" },
    { e: "🔥", n: "fire", k: "lit hot flame", c: "animals" },
    { e: "💧", n: "droplet", k: "water drop", c: "animals" },
    { e: "🌊", n: "water wave", k: "ocean sea", c: "animals" },
    { e: "🌈", n: "rainbow", k: "pride", c: "animals" },
    { e: "☀️", n: "sun", k: "sunny weather", c: "animals" },
    { e: "⛅", n: "sun behind cloud", k: "weather", c: "animals" },
    { e: "☁️", n: "cloud", k: "weather", c: "animals" },
    { e: "❄️", n: "snowflake", k: "cold winter", c: "animals" },

    // ---- food & drink ----
    { e: "🍏", n: "green apple", k: "fruit", c: "food" },
    { e: "🍎", n: "red apple", k: "fruit", c: "food" },
    { e: "🍌", n: "banana", k: "fruit", c: "food" },
    { e: "🍉", n: "watermelon", k: "fruit", c: "food" },
    { e: "🍇", n: "grapes", k: "fruit", c: "food" },
    { e: "🍓", n: "strawberry", k: "fruit", c: "food" },
    { e: "🍑", n: "peach", k: "fruit butt", c: "food" },
    { e: "🍒", n: "cherries", k: "fruit", c: "food" },
    { e: "🍍", n: "pineapple", k: "fruit", c: "food" },
    { e: "🥥", n: "coconut", k: "", c: "food" },
    { e: "🥑", n: "avocado", k: "", c: "food" },
    { e: "🍅", n: "tomato", k: "", c: "food" },
    { e: "🥕", n: "carrot", k: "vegetable", c: "food" },
    { e: "🌽", n: "corn", k: "", c: "food" },
    { e: "🌶️", n: "hot pepper", k: "spicy chili", c: "food" },
    { e: "🥔", n: "potato", k: "", c: "food" },
    { e: "🍞", n: "bread", k: "", c: "food" },
    { e: "🥐", n: "croissant", k: "", c: "food" },
    { e: "🧀", n: "cheese", k: "", c: "food" },
    { e: "🥚", n: "egg", k: "", c: "food" },
    { e: "🍳", n: "cooking", k: "egg fried", c: "food" },
    { e: "🥞", n: "pancakes", k: "breakfast", c: "food" },
    { e: "🥓", n: "bacon", k: "", c: "food" },
    { e: "🍔", n: "hamburger", k: "burger", c: "food" },
    { e: "🍟", n: "french fries", k: "chips", c: "food" },
    { e: "🍕", n: "pizza", k: "", c: "food" },
    { e: "🌭", n: "hot dog", k: "", c: "food" },
    { e: "🌮", n: "taco", k: "mexican", c: "food" },
    { e: "🌯", n: "burrito", k: "", c: "food" },
    { e: "🍜", n: "steaming bowl", k: "ramen noodles", c: "food" },
    { e: "🍝", n: "spaghetti", k: "pasta", c: "food" },
    { e: "🍣", n: "sushi", k: "", c: "food" },
    { e: "🍱", n: "bento box", k: "", c: "food" },
    { e: "🍚", n: "cooked rice", k: "", c: "food" },
    { e: "🍦", n: "soft ice cream", k: "dessert", c: "food" },
    { e: "🍩", n: "doughnut", k: "donut", c: "food" },
    { e: "🍪", n: "cookie", k: "", c: "food" },
    { e: "🎂", n: "birthday cake", k: "celebrate", c: "food" },
    { e: "🍰", n: "shortcake", k: "cake dessert", c: "food" },
    { e: "🍫", n: "chocolate bar", k: "", c: "food" },
    { e: "🍬", n: "candy", k: "sweet", c: "food" },
    { e: "🍭", n: "lollipop", k: "candy", c: "food" },
    { e: "☕", n: "hot beverage", k: "coffee tea", c: "food" },
    { e: "🍵", n: "teacup", k: "tea green", c: "food" },
    { e: "🧃", n: "beverage box", k: "juice", c: "food" },
    { e: "🥤", n: "cup with straw", k: "soda drink", c: "food" },
    { e: "🍺", n: "beer mug", k: "drink", c: "food" },
    { e: "🍻", n: "clinking beer mugs", k: "cheers", c: "food" },
    { e: "🥂", n: "clinking glasses", k: "cheers champagne", c: "food" },
    { e: "🍷", n: "wine glass", k: "drink", c: "food" },
    { e: "🍸", n: "cocktail glass", k: "martini drink", c: "food" },
    { e: "🍾", n: "bottle with popping cork", k: "champagne celebrate", c: "food" },

    // ---- activities ----
    { e: "⚽", n: "soccer ball", k: "football", c: "activities" },
    { e: "🏀", n: "basketball", k: "", c: "activities" },
    { e: "🏈", n: "american football", k: "", c: "activities" },
    { e: "⚾", n: "baseball", k: "", c: "activities" },
    { e: "🎾", n: "tennis", k: "", c: "activities" },
    { e: "🏐", n: "volleyball", k: "", c: "activities" },
    { e: "🏓", n: "ping pong", k: "table tennis", c: "activities" },
    { e: "🏸", n: "badminton", k: "", c: "activities" },
    { e: "🥅", n: "goal net", k: "", c: "activities" },
    { e: "🏒", n: "ice hockey", k: "", c: "activities" },
    { e: "\u{1F3CF}", n: "cricket", k: "bat", c: "activities" },
    { e: "🥊", n: "boxing glove", k: "fight", c: "activities" },
    { e: "🥋", n: "martial arts uniform", k: "karate judo", c: "activities" },
    { e: "🎿", n: "skis", k: "ski snow", c: "activities" },
    { e: "🏂", n: "snowboarder", k: "", c: "activities" },
    { e: "🏆", n: "trophy", k: "win champion award", c: "activities" },
    { e: "🥇", n: "1st place medal", k: "gold win", c: "activities" },
    { e: "🥈", n: "2nd place medal", k: "silver", c: "activities" },
    { e: "🥉", n: "3rd place medal", k: "bronze", c: "activities" },
    { e: "🏅", n: "sports medal", k: "award", c: "activities" },
    { e: "🎯", n: "direct hit", k: "target bullseye dart", c: "activities" },
    { e: "🎮", n: "video game", k: "controller gaming", c: "activities" },
    { e: "🕹️", n: "joystick", k: "game", c: "activities" },
    { e: "🎲", n: "game die", k: "dice", c: "activities" },
    { e: "🎰", n: "slot machine", k: "casino gamble", c: "activities" },
    { e: "🎨", n: "artist palette", k: "art paint", c: "activities" },
    { e: "🎭", n: "performing arts", k: "theater drama", c: "activities" },
    { e: "🎤", n: "microphone", k: "sing karaoke", c: "activities" },
    { e: "🎧", n: "headphone", k: "music listen", c: "activities" },
    { e: "🎸", n: "guitar", k: "music rock", c: "activities" },
    { e: "🎹", n: "musical keyboard", k: "piano music", c: "activities" },
    { e: "🥁", n: "drum", k: "music", c: "activities" },
    { e: "🎺", n: "trumpet", k: "music", c: "activities" },
    { e: "🎻", n: "violin", k: "music", c: "activities" },
    { e: "🎬", n: "clapper board", k: "movie film", c: "activities" },
    { e: "🎉", n: "party popper", k: "celebrate tada", c: "activities" },
    { e: "🎊", n: "confetti ball", k: "celebrate", c: "activities" },
    { e: "🎈", n: "balloon", k: "party", c: "activities" },
    { e: "🎁", n: "wrapped gift", k: "present birthday", c: "activities" },

    // ---- travel & places ----
    { e: "🚗", n: "car", k: "automobile", c: "travel" },
    { e: "🚕", n: "taxi", k: "cab", c: "travel" },
    { e: "🚙", n: "sport utility vehicle", k: "suv", c: "travel" },
    { e: "🚌", n: "bus", k: "", c: "travel" },
    { e: "🏎️", n: "racing car", k: "f1 fast", c: "travel" },
    { e: "🚓", n: "police car", k: "", c: "travel" },
    { e: "🚑", n: "ambulance", k: "emergency", c: "travel" },
    { e: "🚒", n: "fire engine", k: "", c: "travel" },
    { e: "🚲", n: "bicycle", k: "bike", c: "travel" },
    { e: "🛵", n: "motor scooter", k: "vespa", c: "travel" },
    { e: "🏍️", n: "motorcycle", k: "bike", c: "travel" },
    { e: "✈️", n: "airplane", k: "flight travel", c: "travel" },
    { e: "🚀", n: "rocket", k: "space launch ship", c: "travel" },
    { e: "🛸", n: "flying saucer", k: "ufo alien", c: "travel" },
    { e: "🚁", n: "helicopter", k: "", c: "travel" },
    { e: "⛵", n: "sailboat", k: "boat", c: "travel" },
    { e: "🚢", n: "ship", k: "cruise boat", c: "travel" },
    { e: "🚂", n: "locomotive", k: "train", c: "travel" },
    { e: "🚆", n: "train", k: "", c: "travel" },
    { e: "🗺️", n: "world map", k: "travel", c: "travel" },
    { e: "🗽", n: "statue of liberty", k: "new york usa", c: "travel" },
    { e: "🗼", n: "tokyo tower", k: "", c: "travel" },
    { e: "🏰", n: "castle", k: "", c: "travel" },
    { e: "🏠", n: "house", k: "home", c: "travel" },
    { e: "🏡", n: "house with garden", k: "home", c: "travel" },
    { e: "🏢", n: "office building", k: "work", c: "travel" },
    { e: "🏥", n: "hospital", k: "", c: "travel" },
    { e: "🏦", n: "bank", k: "", c: "travel" },
    { e: "🏨", n: "hotel", k: "", c: "travel" },
    { e: "⛺", n: "tent", k: "camping", c: "travel" },
    { e: "🌋", n: "volcano", k: "", c: "travel" },
    { e: "🏔️", n: "snow capped mountain", k: "", c: "travel" },
    { e: "🏖️", n: "beach with umbrella", k: "vacation", c: "travel" },
    { e: "🗿", n: "moai", k: "easter island statue", c: "travel" },
    { e: "🎡", n: "ferris wheel", k: "fair", c: "travel" },
    { e: "🎢", n: "roller coaster", k: "theme park", c: "travel" },
    { e: "🌃", n: "night with stars", k: "city night", c: "travel" },
    { e: "🌉", n: "bridge at night", k: "", c: "travel" },

    // ---- objects ----
    { e: "💡", n: "light bulb", k: "idea", c: "objects" },
    { e: "🔦", n: "flashlight", k: "torch", c: "objects" },
    { e: "🔋", n: "battery", k: "power", c: "objects" },
    { e: "🔌", n: "electric plug", k: "power", c: "objects" },
    { e: "💻", n: "laptop", k: "computer pc code", c: "objects" },
    { e: "🖥️", n: "desktop computer", k: "pc monitor", c: "objects" },
    { e: "⌨️", n: "keyboard", k: "type", c: "objects" },
    { e: "🖱️", n: "computer mouse", k: "", c: "objects" },
    { e: "💾", n: "floppy disk", k: "save", c: "objects" },
    { e: "💿", n: "optical disk", k: "cd", c: "objects" },
    { e: "📱", n: "mobile phone", k: "smartphone iphone", c: "objects" },
    { e: "📞", n: "telephone receiver", k: "call phone", c: "objects" },
    { e: "📷", n: "camera", k: "photo", c: "objects" },
    { e: "📸", n: "camera with flash", k: "photo", c: "objects" },
    { e: "🎥", n: "movie camera", k: "film", c: "objects" },
    { e: "📺", n: "television", k: "tv", c: "objects" },
    { e: "🔍", n: "magnifying glass", k: "search zoom find", c: "objects" },
    { e: "🔒", n: "locked", k: "lock secure private", c: "objects" },
    { e: "🔓", n: "unlocked", k: "open", c: "objects" },
    { e: "🔑", n: "key", k: "password", c: "objects" },
    { e: "🔨", n: "hammer", k: "tool build", c: "objects" },
    { e: "🛠️", n: "hammer and wrench", k: "tools fix", c: "objects" },
    { e: "🔧", n: "wrench", k: "tool fix", c: "objects" },
    { e: "⚙️", n: "gear", k: "settings cog config", c: "objects" },
    { e: "🧰", n: "toolbox", k: "tools", c: "objects" },
    { e: "🧲", n: "magnet", k: "", c: "objects" },
    { e: "💣", n: "bomb", k: "explode", c: "objects" },
    { e: "💊", n: "pill", k: "medicine", c: "objects" },
    { e: "💉", n: "syringe", k: "shot vaccine", c: "objects" },
    { e: "🩺", n: "stethoscope", k: "doctor", c: "objects" },
    { e: "💰", n: "money bag", k: "cash rich", c: "objects" },
    { e: "💵", n: "dollar banknote", k: "money cash", c: "objects" },
    { e: "💳", n: "credit card", k: "payment", c: "objects" },
    { e: "💎", n: "gem stone", k: "diamond jewel", c: "objects" },
    { e: "⚖️", n: "balance scale", k: "justice law", c: "objects" },
    { e: "🔗", n: "link", k: "chain url", c: "objects" },
    { e: "📎", n: "paperclip", k: "attach", c: "objects" },
    { e: "📌", n: "pushpin", k: "pin location", c: "objects" },
    { e: "📍", n: "round pushpin", k: "location map", c: "objects" },
    { e: "✏️", n: "pencil", k: "write edit", c: "objects" },
    { e: "🖊️", n: "pen", k: "write", c: "objects" },
    { e: "📝", n: "memo", k: "note write", c: "objects" },
    { e: "📖", n: "open book", k: "read", c: "objects" },
    { e: "📚", n: "books", k: "library study", c: "objects" },
    { e: "📅", n: "calendar", k: "date schedule", c: "objects" },
    { e: "📈", n: "chart increasing", k: "growth stats up", c: "objects" },
    { e: "📉", n: "chart decreasing", k: "loss down", c: "objects" },
    { e: "✉️", n: "envelope", k: "email mail", c: "objects" },
    { e: "📦", n: "package", k: "box shipping", c: "objects" },
    { e: "🗑️", n: "wastebasket", k: "trash delete bin", c: "objects" },
    { e: "🔔", n: "bell", k: "notification alert", c: "objects" },
    { e: "⏰", n: "alarm clock", k: "time wake", c: "objects" },
    { e: "⏳", n: "hourglass not done", k: "time wait loading", c: "objects" },

    // ---- symbols ----
    { e: "❤️", n: "red heart", k: "love like", c: "symbols" },
    { e: "🧡", n: "orange heart", k: "love", c: "symbols" },
    { e: "💛", n: "yellow heart", k: "love", c: "symbols" },
    { e: "💚", n: "green heart", k: "love", c: "symbols" },
    { e: "💙", n: "blue heart", k: "love", c: "symbols" },
    { e: "💜", n: "purple heart", k: "love", c: "symbols" },
    { e: "🖤", n: "black heart", k: "love", c: "symbols" },
    { e: "🤍", n: "white heart", k: "love", c: "symbols" },
    { e: "💔", n: "broken heart", k: "sad heartbreak", c: "symbols" },
    { e: "❣️", n: "heart exclamation", k: "love", c: "symbols" },
    { e: "💕", n: "two hearts", k: "love", c: "symbols" },
    { e: "💯", n: "hundred points", k: "100 perfect score", c: "symbols" },
    { e: "💢", n: "anger symbol", k: "mad", c: "symbols" },
    { e: "💥", n: "collision", k: "boom explode", c: "symbols" },
    { e: "💫", n: "dizzy", k: "stars", c: "symbols" },
    { e: "💬", n: "speech balloon", k: "chat comment talk", c: "symbols" },
    { e: "💭", n: "thought balloon", k: "think", c: "symbols" },
    { e: "✅", n: "check mark button", k: "yes done correct ok", c: "symbols" },
    { e: "✔️", n: "check mark", k: "yes done tick", c: "symbols" },
    { e: "❌", n: "cross mark", k: "no wrong error x", c: "symbols" },
    { e: "❓", n: "question mark", k: "help", c: "symbols" },
    { e: "❗", n: "exclamation mark", k: "warning important", c: "symbols" },
    { e: "⚠️", n: "warning", k: "caution alert", c: "symbols" },
    { e: "🚫", n: "prohibited", k: "no forbidden ban", c: "symbols" },
    { e: "♻️", n: "recycling symbol", k: "recycle eco", c: "symbols" },
    { e: "🔄", n: "counterclockwise arrows", k: "refresh sync reload", c: "symbols" },
    { e: "➡️", n: "right arrow", k: "next", c: "symbols" },
    { e: "⬅️", n: "left arrow", k: "back", c: "symbols" },
    { e: "⬆️", n: "up arrow", k: "", c: "symbols" },
    { e: "⬇️", n: "down arrow", k: "", c: "symbols" },
    { e: "🔼", n: "upwards button", k: "", c: "symbols" },
    { e: "▶️", n: "play button", k: "start", c: "symbols" },
    { e: "⏸️", n: "pause button", k: "", c: "symbols" },
    { e: "⏹️", n: "stop button", k: "", c: "symbols" },
    { e: "🔀", n: "shuffle", k: "random", c: "symbols" },
    { e: "🔁", n: "repeat", k: "loop", c: "symbols" },
    { e: "➕", n: "plus", k: "add", c: "symbols" },
    { e: "➖", n: "minus", k: "subtract", c: "symbols" },
    { e: "✖️", n: "multiply", k: "times", c: "symbols" },
    { e: "➗", n: "divide", k: "", c: "symbols" },
    { e: "🟰", n: "heavy equals sign", k: "equal", c: "symbols" },
    { e: "💲", n: "heavy dollar sign", k: "money", c: "symbols" },
    { e: "©️", n: "copyright", k: "", c: "symbols" },
    { e: "®️", n: "registered", k: "", c: "symbols" },
    { e: "™️", n: "trade mark", k: "tm", c: "symbols" },
    { e: "🔴", n: "red circle", k: "dot", c: "symbols" },
    { e: "🟢", n: "green circle", k: "dot online", c: "symbols" },
    { e: "🔵", n: "blue circle", k: "dot", c: "symbols" },
    { e: "⚫", n: "black circle", k: "dot", c: "symbols" },
    { e: "⭕", n: "hollow red circle", k: "o", c: "symbols" },
    { e: "🔺", n: "red triangle up", k: "", c: "symbols" },
    { e: "💤", n: "zzz", k: "sleep tired", c: "symbols" },
    { e: "🆗", n: "ok button", k: "okay", c: "symbols" },
    { e: "🆕", n: "new button", k: "", c: "symbols" },
    { e: "🆒", n: "cool button", k: "", c: "symbols" },
    { e: "🈚", n: "free of charge", k: "", c: "symbols" },

    // ---- flags ----
    { e: "🏁", n: "chequered flag", k: "race finish", c: "flags" },
    { e: "🚩", n: "triangular flag", k: "", c: "flags" },
    { e: "🏴", n: "black flag", k: "", c: "flags" },
    { e: "🏳️", n: "white flag", k: "surrender", c: "flags" },
    { e: "🏳️‍🌈", n: "rainbow flag", k: "pride lgbt", c: "flags" },
    { e: "🏴‍☠️", n: "pirate flag", k: "skull", c: "flags" },
    { e: "🇺🇸", n: "flag united states", k: "usa america", c: "flags" },
    { e: "🇬🇧", n: "flag united kingdom", k: "uk britain", c: "flags" },
    { e: "🇫🇷", n: "flag france", k: "french", c: "flags" },
    { e: "🇩🇪", n: "flag germany", k: "german", c: "flags" },
    { e: "🇪🇸", n: "flag spain", k: "spanish", c: "flags" },
    { e: "🇮🇹", n: "flag italy", k: "italian", c: "flags" },
    { e: "🇯🇵", n: "flag japan", k: "japanese", c: "flags" },
    { e: "🇨🇳", n: "flag china", k: "chinese", c: "flags" },
    { e: "🇰🇷", n: "flag south korea", k: "korean", c: "flags" },
    { e: "🇨🇦", n: "flag canada", k: "canadian", c: "flags" },
    { e: "🇧🇷", n: "flag brazil", k: "brazilian", c: "flags" },
    { e: "🇮🇳", n: "flag india", k: "indian", c: "flags" },
    { e: "🇷🇺", n: "flag russia", k: "russian", c: "flags" },
    { e: "🇲🇽", n: "flag mexico", k: "mexican", c: "flags" },
    { e: "🇳🇱", n: "flag netherlands", k: "dutch", c: "flags" },
    { e: "🇵🇹", n: "flag portugal", k: "portuguese", c: "flags" },
    { e: "🇸🇪", n: "flag sweden", k: "swedish", c: "flags" }
]

function byCategory(cat) {
    var out = []
    for (var i = 0; i < EMOJI.length; i++)
        if (EMOJI[i].c === cat) out.push(EMOJI[i])
    return out
}

function search(query) {
    // tokenized AND search: every word must match somewhere in name+keywords
    // ("heart red" now finds the red heart; single-token behaves as before)
    var q = (query || "").toLowerCase().trim()
    if (q.length === 0) return []
    var tokens = q.split(/\s+/)
    var out = []
    for (var i = 0; i < EMOJI.length; i++) {
        var em = EMOJI[i]
        var hay = em.n + " " + (em.k || "")
        var ok = true
        for (var t = 0; t < tokens.length; t++) {
            if (hay.indexOf(tokens[t]) === -1) { ok = false; break }
        }
        if (ok) out.push(em)
    }
    return out
}

// ---- skin tones ----
// modifier bases present in this dataset (hands & gestures); the panel shows
// a 6-variant strip on right-click / long-press for these
var TONEABLE = {
    "👋": 1, "🤚": 1, "✋": 1, "🖐️": 1, "👌": 1, "🤌": 1, "🤏": 1, "✌️": 1, "🤞": 1, "🤟": 1,
    "🤘": 1, "🤙": 1, "👈": 1, "👉": 1, "👆": 1, "👇": 1, "☝️": 1, "👍": 1, "👎": 1, "✊": 1,
    "👊": 1, "🤛": 1, "🤜": 1, "👏": 1, "🙌": 1, "👐": 1, "🤲": 1, "🤝": 1, "🙏": 1, "✍️": 1, "💪": 1
}
var TONES = ["", "\u{1F3FB}", "\u{1F3FC}", "\u{1F3FD}", "\u{1F3FE}", "\u{1F3FF}"]
function toneable(e) { return TONEABLE[e] === 1 }

// resolve a (possibly toned) char back to its dataset entry char — keeps the
// variation selector intact (✌🏽 -> ✌️), so default variants render in colour
function datasetBase(ch) {
    if (!ch) return ch
    var b = ch.replace(/\uD83C[\uDFFB-\uDFFF]/g, "").replace(/️/g, "")
    for (var i = 0; i < EMOJI.length; i++)
        if (EMOJI[i].e.replace(/️/g, "") === b) return EMOJI[i].e
    return ch
}

// reverse lookup for the footer preview: emoji char (possibly toned) -> name
function nameOf(ch) {
    if (!ch) return ""
    // strip skin-tone modifiers (U+1F3FB..FF) and variation selectors first
    var base = ch.replace(/\uD83C[\uDFFB-\uDFFF]/g, "").replace(/️/g, "")
    for (var i = 0; i < EMOJI.length; i++) {
        var ee = EMOJI[i].e
        if (ee === ch || ee.replace(/️/g, "") === base) return EMOJI[i].n
    }
    return ""
}
function withTone(e, tone) {
    if (!tone) return e
    // the skin-tone modifier replaces any emoji variation selector (✌️ -> ✌🏽)
    return e.replace(/️/g, "") + tone
}
